// Generated by CoffeeScript 1.10.0
(function() {
  var Filter;

  module.exports = Filter = (function() {
    function Filter(predicate) {
      this.predicate = predicate;
      this.conditions = [];
    }

    Filter.prototype.addIndividualCondition = function(operation, individual) {
      return this.conditions.push({
        operation: operation,
        individual: individual.id,
        conditiontype: 'individual'
      });
    };

    Filter.prototype.addValueCondition = function(operation, value) {
      return this.conditions.push({
        operation: operation,
        value: value,
        conditiontype: 'value'
      });
    };

    Filter.prototype.addViewCondition = function(operation, view) {
      return this.conditions.push({
        operation: operation,
        view: view.id,
        conditiontype: 'view'
      });
    };

    return Filter;

  })();

}).call(this);
