// Generated by CoffeeScript 1.10.0
(function() {
  var Individual;

  module.exports = Individual = (function() {
    function Individual(id) {
      this.id = id;
    }

    return Individual;

  })();

}).call(this);
