// Generated by CoffeeScript 1.10.0
(function() {
  var IndividualProperty;

  module.exports = IndividualProperty = (function() {
    function IndividualProperty(id, subject, predicate, object) {
      this.id = id;
      this.subject = subject;
      this.predicate = predicate;
      this.object = object;
    }

    return IndividualProperty;

  })();

}).call(this);
