// Generated by CoffeeScript 1.10.0
(function() {
  var ValueProperty;

  module.exports = ValueProperty = (function() {
    function ValueProperty(id, subject, predicate, object) {
      this.id = id;
      this.subject = subject;
      this.predicate = predicate;
      this.object = object;
    }

    return ValueProperty;

  })();

}).call(this);
