// Generated by CoffeeScript 1.10.0
(function() {
  var Filter, Individual, IndividualProperty, ValueProperty;

  Individual = require('./model/individual');

  IndividualProperty = require('./model/individualProperty');

  ValueProperty = require('./model/valueProperty');

  Filter = require('./model/filter');

  module.exports = {
    Individual: Individual,
    IndividualProperty: IndividualProperty,
    ValueProperty: ValueProperty,
    Filter: Filter
  };

}).call(this);
